sonar.projectKey=pllee4_algorithm
sonar.organization=pllee4
sonar.projectName=algorithm

# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================

# SQ standard properties
sonar.sources=src, include