name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          artifact: package
          name: Test report
          path: test-reports/*.xml
          reporter: jest-junit